vince: QCamera2: Wrap LOGE macro with braces in ADD_SET_PARAM_ENTRY_TO_BATCH
Wrap LOGE macro with braces in ADD_SET_PARAM_ENTRY_TO_BATCH macro to
avoid new clang-12 compound punctuation token warning

QCamera2/HAL/QCamera2HWICallbacks.cpp:2158:5: error: '(' and '{' tokens
introducing statement expression appear in different macro expansion
contexts [-Werror,-Wcompound-token-split-by-macro]
    ADD_SET_PARAM_ENTRY_TO_BATCH(pMetaData,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QCamera2/stack/common/cam_intf.h:858:6: note: expanded from macro 'ADD_SET_PARAM_ENTRY_TO_BATCH'
    ((LOGE("Unable to set metadata TABLE_PTR:%p META_ID:%d", \
     ^
QCamera2/HAL/QCamera2HWICallbacks.cpp:2158:5: note: '{' token is here
    ADD_SET_PARAM_ENTRY_TO_BATCH(pMetaData,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QCamera2/stack/common/cam_intf.h:858:7: note: expanded from macro 'ADD_SET_PARAM_ENTRY_TO_BATCH'
    ((LOGE("Unable to set metadata TABLE_PTR:%p META_ID:%d", \
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QCamera2/stack/mm-camera-interface/inc/mm_camera_dbg.h:105:28: note: expanded from macro 'LOGE'
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QCamera2/stack/mm-camera-interface/inc/mm_camera_dbg.h:90:5: note: expanded from macro 'CLOGE'
    CLOGx(module, CAM_GLBL_DBG_ERR, fmt, ##args)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QCamera2/stack/mm-camera-interface/inc/mm_camera_dbg.h:66:68: note: expanded from macro 'CLOGx'
                                                                   ^

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
Change-Id: I07388378044e1d6c323e8241752a7464395b1334
Signed-off-by: GhostMaster69-dev <rathore6375@gmail.com>